---

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install packages for debian system
  become: true
  apt: name={{ item }} state=present
  with_items:
    - "{{ main_packages }}"
    - "{{ os_packages }}"
    - "{{ python_package_modules }}"
  when: ansible_os_family=='Debian'
